[build]
  command = "yarn build"
  publish = "public"

[context.branch-deploy]
  command = "yarn build-storybook"
  publish = "storybook"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
